Last Updated: 08-10-2017

# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Statistics-(scipy.stats)" data-toc-modified-id="Statistics-(scipy.stats)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Statistics (<code>scipy.stats</code>)</a></div><div class="lev2 toc-item"><a href="#Random-Variables" data-toc-modified-id="Random-Variables-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Random Variables</a></div><div class="lev3 toc-item"><a href="#Common-Methods" data-toc-modified-id="Common-Methods-111"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Common Methods</a></div><div class="lev3 toc-item"><a href="#Shifting-and-Scaling" data-toc-modified-id="Shifting-and-Scaling-112"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Shifting and Scaling</a></div><div class="lev3 toc-item"><a href="#Shape-Parameters" data-toc-modified-id="Shape-Parameters-113"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Shape Parameters</a></div><div class="lev3 toc-item"><a href="#Freezing-a-Distribution" data-toc-modified-id="Freezing-a-Distribution-114"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>Freezing a Distribution</a></div><div class="lev3 toc-item"><a href="#Broadcasting" data-toc-modified-id="Broadcasting-115"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>Broadcasting</a></div><div class="lev2 toc-item"><a href="#Building-Specific-Distributions" data-toc-modified-id="Building-Specific-Distributions-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Building Specific Distributions</a></div><div class="lev3 toc-item"><a href="#Making-a-Continuous-Distribution" data-toc-modified-id="Making-a-Continuous-Distribution-121"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Making a Continuous Distribution</a></div>

# Statistics (```scipy.stats```)

In [14]:
from scipy import stats
from scipy.stats import norm 
import numpy as np
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
matplotlib.style.use('seaborn')
matplotlib.rcParams['figure.figsize'] = (12, 15)
import pandas as pd
import seaborn as sns

## Random Variables

There are two general distribution classes:
- [**continuous random variables**](https://docs.scipy.org/doc/scipy/reference/tutorial/stats/continuous.html#continuous-random-variables)
- [**discrete random variables**](https://docs.scipy.org/doc/scipy/reference/tutorial/stats/discrete.html#discrete-random-variables)

### Common Methods

The main public methods for continous Random Variables are:
- rvs: Random variates
- pdf: Probability Density Function
- cdf: Cumulative Distribution Function
- sf: Survival Function (1-CDF)
- ppf: Percent Point Function (inverse of CDF)
- isf: Inverse Survival Function (inverse of SF)
- stats: Return mean, variance, skew, or kurtosis
- moment: non-central moments of the distribution

In [15]:
# a normal RV 
norm.cdf(0)

0.5

In [16]:
# To compute the cdf at a number of points
norm.cdf([-1., 0, 1])

array([ 0.15865525,  0.5       ,  0.84134475])

In [12]:
a = np.random.rand(10)
a.sort()
a

array([ 0.18559222,  0.31226478,  0.34864598,  0.35558579,  0.52853844,
        0.63134635,  0.81389615,  0.82407723,  0.88141108,  0.9517115 ])

In [17]:
# To compute the cdf at a number of points
norm.cdf(a)

array([ 0.57361772,  0.62258035,  0.63632245,  0.63892461,  0.70143716,
        0.73609295,  0.79214778,  0.79505216,  0.81095232,  0.82937834])

- Thus, the basic methods such as pdf, cdf, and so on are vectorized with ```np.vectorize```.

Other generally useful methods are supported too:

In [19]:
norm.mean(), norm.std(), norm.var()

(0.0, 1.0, 1.0)

In [20]:
norm.stats(moments="mv")

(array(0.0), array(1.0))

- To find the median of a distribution we can use the percent point function ppf, which is the inverse of the cdf:

In [21]:
norm.ppf(0.5)

0.0

- To generate a sequence of random variates, use the ```size``` keyword argument:



In [25]:
norm.rvs(size=5, random_state=1234)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873])

In [27]:
norm.rvs(size=5, random_state=1234)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873])

### Shifting and Scaling

- All continuous distributions take ```loc``` and ```scale``` as keyword parameters to adjust the location and scale of the distribution, e.g. for the standard normal distribution the location is the mean and the scale is the standard deviation.

In [28]:
norm.stats(loc=3, scale=4, moments = "mv")

(array(3.0), array(16.0))

In many cases the standardized distribution for a random variable ```X``` is obtained through the transformation ```(X - loc) / scale```. The default values are ```loc = 0``` and ```scale = 1```.

Smart use of ```loc``` and ```scale``` can help modify the standard distributions in many ways. To illustrate the scaling further, the ```cdf``` of an exponentially distributed RV with mean $1/λ$ given by:
$$F(x)=1-exp(-λx)$$

By applying the scaling rule above, it can be seen that by taking ```scale  = 1./lambda``` we get the proper scale

In [29]:
from scipy.stats import expon

In [30]:
expon.mean(scale=3.)

3.0

In [31]:
from scipy.stats import uniform

In [32]:
uniform.cdf(np.arange(6), loc=1, scale=4)

array([ 0.  ,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

### Shape Parameters

While a general continuous random variable can be shifted and scaled with the ```loc``` and ```scale``` parameters, some distributions require additional shape parameters. For instance, the gamma distribution, with density:

$$\gamma(x, a) = \frac{\lambda (\lambda x)^{a-1}}{\Gamma(a)} e^{-\lambda x}\;,$$

requires the shape parameter aa. Observe that setting $\lambda$ can be obtained by setting the scale keyword to $1/\lambda$.

In [33]:
from scipy.stats import gamma

In [34]:
gamma.numargs

1

In [35]:
gamma.shapes

'a'

- Now we set the value of the shape variable to 1 to obtain the exponential distribution, so that we compare easily whether we get the results we expect.

In [36]:
gamma(1, scale=2.).stats(moments="mv")

(array(2.0), array(4.0))

In [37]:
gamma(a=1, scale=2.).stats(moments="mv")

(array(2.0), array(4.0))

### Freezing a Distribution

Passing the ```loc``` and ```scale``` keywords time and again can become quite bothersome. The concept of freezing a RV is used to solve such problems.



In [40]:
rv = gamma(1, scale=2.)
print(rv)

By using rv we no longer have to include the scale or the shape parameters anymore. Thus, distributions can be used in one of two ways, either by passing all distribution parameters to each method call or by freezing the parameters for the instance of the distribution. 

In [41]:
rv.mean(), rv.std()

(2.0, 2.0)

### Broadcasting

The basic methods pdf and so on satisfy the usual numpy broadcasting rules. For example, we can calculate the critical values for the upper tail of the t distribution for different probabilities and degrees of freedom.

In [42]:
stats.t.isf([0.1, 0.05, 0.01], [[10], [11]])

array([[ 1.37218364,  1.81246112,  2.76376946],
       [ 1.36343032,  1.79588482,  2.71807918]])

Here, the first row are the critical values for 10 degrees of freedom and the second row for 11 degrees of freedom (d.o.f.). Thus, the broadcasting rules give the same result of calling isf twice:

In [43]:
stats.t.isf([0.1, 0.05, 0.01], 10)

array([ 1.37218364,  1.81246112,  2.76376946])

In [44]:
stats.t.isf([0.1, 0.05, 0.01], 11)


array([ 1.36343032,  1.79588482,  2.71807918])

If the array with probabilities, i.e., ```[0.1, 0.05, 0.01]``` and the array of degrees of freedom i.e., ```[10, 11, 12]```, have the same array shape, then element wise matching is used. As an example, we can obtain the 10% tail for 10 d.o.f., the 5% tail for 11 d.o.f. and the 1% tail for 12 d.o.f. by calling

In [46]:
stats.t.isf([0.1, 0.05, 0.01], [10, 11, 12])

array([ 1.37218364,  1.79588482,  2.68099799])

## Building Specific Distributions

### Making a Continuous Distribution

In [47]:
class deterministic_gen(stats.rv_continuous):
    def _cdf(self, x):
        return np.where(x < 0, 0., 1.)
    
    def _stats(self):
        return 0., 0., 0., 0.

In [48]:
deterministic = deterministic_gen(name="deterministic")

In [49]:
deterministic.cdf(np.arange(-3, 3, 0.5))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.])

In [56]:
deterministic.pdf(np.arange(-3, 3, 0.5))

array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         5.83333333e+04,   4.16333634e-12,   4.16333634e-12,
         4.16333634e-12,   4.16333634e-12,   4.16333634e-12])